/**
 * Space game typings
 * by EdJoPaTo
 * AGPL-3.0-or-later
 * TODO: repolink
 */

export type LifelessIdentifier = `lifeless${number}`;
export type ModulePassiveIdentifier = `modp${number}`;
export type ModuleSelfIdentifier = `mods${number}`;
export type ModuleTargetedIdentifier = `modt${number}`;

/** Example: player-tg-1337 */
export type PlayerIdentifier = `player-${string}-${number}`;
export type PlayerTelegramIdentifier = `player-tg-${number}`;

export type SitesNearPlanet = Record<number, readonly SiteInfo[]>;

/* Autogenerated after here */
