name: Test and Build Rust

on:
  push:
  pull_request:

jobs:
  test:
    name: Test ${{ matrix.os }} ${{ matrix.toolchain }}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            toolchain: stable
            clippyargs: -D clippy::pedantic -D warnings
            experimental: false
    steps:
      - uses: actions/checkout@v2

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          components: clippy
          override: true
          profile: minimal
          toolchain: ${{ matrix.toolchain }}

      - name: Run clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --verbose --locked --all-targets --all-features -- ${{ matrix.clippyargs }}

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose --locked --all-features

  github-release:
    name: Release ${{ matrix.triple }}
    runs-on: ${{ matrix.os }}
    needs: test
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            triple: x86_64-unknown-linux-gnu
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set Artifact Name
        shell: bash
        run: |
          version=$(git describe --tags --match "v*.*.*" --always)
          echo "version is: $version"
          echo "GIT_TAG_VERSION=$version" >> $GITHUB_ENV

          name="backend-$version-${{ matrix.triple }}"
          echo "artifact name is: $name"
          echo "ARTIFACT_NAME=$name" >> $GITHUB_ENV

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          override: true
          profile: minimal
          target: ${{ matrix.triple }}
          toolchain: stable

      - name: Build
        uses: actions-rs/cargo@v1
        env:
          # TODO: Remove this once it's the default
          SDKROOT: /Library/Developer/CommandLineTools/SDKs/MacOSX11.1.sdk
        with:
          command: build
          args: --release --verbose --locked --all-features --target ${{ matrix.triple }}
          use-cross: ${{ runner.os == 'Linux' && matrix.triple != 'x86_64-unknown-linux-gnu' }}

      - name: Package (-nix)
        if: runner.os != 'Windows'
        run: >
          tar --gzip -cvf ${{ env.ARTIFACT_NAME }}.tar.gz
          completions LICENSE README.md
          systemd/**/*.service systemd/**/*.timer systemd/**/*.conf
          -C target/${{ matrix.triple }}/release backend
      - name: Package (windows)
        if: runner.os == 'Windows'
        run: |
          7z a ${{ env.ARTIFACT_NAME }}.zip completions LICENSE README.md
          cd target/${{ matrix.triple }}/release
          7z a ../../../${{ env.ARTIFACT_NAME }}.zip backend.exe
          cd -

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.triple }}
          path: |
            *.zip
            *.tar.gz

      - name: GitHub Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *.zip
            *.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
